# Generated by Django 4.0 on 2022-10-31 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=300)),
                ('module', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('surname', models.CharField(max_length=300)),
                ('age', models.CharField(max_length=300)),
                ('sex', models.CharField(max_length=300)),
                ('phonenumber', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
            ],
        ),
    ]
