# Generated by Django 4.0 on 2022-10-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectuer_full_name', models.CharField(max_length=300)),
                ('department', models.CharField(choices=[('Science and Technology', 'Science and Technology'), ('Commercials', 'Commercials'), ('Arts', 'Arts'), ('Medicine', 'Medicine'), ('Law', 'Law')], max_length=300)),
                ('student_full_name', models.CharField(max_length=300)),
                ('student_reg', models.CharField(max_length=300)),
                ('student_email', models.EmailField(max_length=300)),
                ('appointment_date', models.CharField(max_length=300)),
                ('appointment_time', models.CharField(max_length=300)),
                ('duration', models.CharField(max_length=300)),
                ('aim', models.CharField(max_length=300)),
                ('phonenumber', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Apply',
        ),
    ]
