# Generated by Django 4.0 on 2022-11-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_appointment_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.CharField(choices=[('5mins', '5mins'), ('10mins', '10mins'), ('15mins', '15mins'), ('20mins', '20mins'), ('25mins', '25mins'), ('30mins', '35mins'), ('45mins', '45mins'), ('1hour', '1hour')], max_length=300),
        ),
    ]
