# Generated by Django 4.0 on 2022-11-02 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='lectuer_full_name',
            new_name='lecturer_full_name',
        ),
    ]
