# Generated by Django 4.0 on 2022-11-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_lectuer_full_name_appointment_lecturer_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='statuses',
            field=models.CharField(choices=[('pending...', 'pending...'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending...', max_length=300),
        ),
    ]
